# Generated by Django 3.2.4 on 2021-06-24 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company_logo',
            field=models.ImageField(default='https://previews.123rf.com/images/arcady31/arcady311509/arcady31150900028/46164370-job-vacancy-rubber-stamp.jpg', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 6, 24, 10, 0, 49, 268906, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='qualifications',
            field=tinymce.models.HTMLField(),
        ),
    ]
