# Generated by Django 3.2.4 on 2021-06-24 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_alter_vacancy_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 6, 24, 18, 39, 12, 340209, tzinfo=utc)),
        ),
    ]
