# Generated by Django 3.2.4 on 2021-06-26 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_auto_20210624_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 9, 17, 16, 37549, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
