# Generated by Django 3.2.4 on 2021-06-27 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0010_alter_vacancy_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company_logo',
            field=models.ImageField(default='vacancy.jpg', upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 6, 27, 12, 34, 12, 740205, tzinfo=utc)),
        ),
    ]
