# Generated by Django 3.2.4 on 2021-06-27 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0011_auto_20210627_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 6, 27, 13, 6, 11, 467663, tzinfo=utc)),
        ),
    ]
