# Generated by Django 3.2.4 on 2021-06-27 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0012_alter_vacancy_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 6, 27, 15, 19, 22, 138253, tzinfo=utc)),
        ),
    ]
