# Generated by Django 3.2.4 on 2021-06-28 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0013_alter_vacancy_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 15, 38, 34, 500269, tzinfo=utc)),
        ),
    ]
