# Generated by Django 3.2.4 on 2021-06-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0014_alter_vacancy_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
