# Generated by Django 3.2.4 on 2021-06-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['date_posted'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(editable=False, max_length=350),
        ),
    ]
